# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jordan Bunke
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Jordan Bunke, London-based software developer and writer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jbunke.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jbunke
email: jordanbunkework@gmail.com

# Build settings
markdown: GFM
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:collection/:name
  experience:
    output: false
  posts:
    permalink: /blog/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
